import { ElementRef, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { NgxMaterialTimepickerComponent } from '../ngx-material-timepicker.component';
import { ControlValueAccessor } from '@angular/forms';
import { DateTime } from 'luxon';
export declare class TimepickerDirective implements ControlValueAccessor, OnDestroy, OnChanges {
    elementRef: ElementRef;
    private locale;
    set format(value: number);
    get format(): number;
    private _format;
    set min(value: string | DateTime);
    get min(): string | DateTime;
    private _min;
    set max(value: string | DateTime);
    get max(): string | DateTime;
    private _max;
    set timepicker(picker: NgxMaterialTimepickerComponent);
    private _timepicker;
    set value(value: string);
    get value(): string;
    private _value;
    disabled: boolean;
    disableClick: boolean;
    private timepickerSubscriptions;
    private previousFormat;
    onTouched: () => void;
    private onChange;
    constructor(elementRef: ElementRef, locale: string);
    private set defaultTime(value);
    onInput(value: string): void;
    ngOnChanges(changes: SimpleChanges): void;
    onClick(event: any): void;
    writeValue(value: string): void;
    registerOnChange(fn: (value: any) => void): void;
    registerOnTouched(fn: () => void): void;
    setDisabledState(isDisabled: boolean): void;
    ngOnDestroy(): void;
    private registerTimepicker;
    private updateInputValue;
}
